<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="12" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestConvertNetmaskBitsToBinary-20201010100305" skipped="0" tests="12" time="0.225" timestamp="2020-10-10T10:03:06">
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_maximum_ipv4_netmask" time="0.005" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11111111.11111111.11111110' != '.11111111.11111111.11111111.11111110'
- 11111111.11111111.11111111.11111110
+ .11111111.11111111.11111111.11111110
? +
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 713, in test_maximum_ipv4_netmask
    self.assertEquals('11111111.11111111.11111111.11111110', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111110' != '.11111111.11111111.11111111.11111110'
- 11111111.11111111.11111111.11111110
+ .11111111.11111111.11111111.11111110
? +

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_maximum_ipv6_netmask" time="0.035" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11111111.11111111.11111111.11111[98 chars]1111' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111
?                  -                 -                 -                 -                 -                 -                 -         ^^^^^^^^
+ .1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000
? +++++++++                                                                                                                                ^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 743, in test_maximum_ipv6_netmask
    self.assertEquals('11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111111.11111[98 chars]1111' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111
?                  -                 -                 -                 -                 -                 -                 -         ^^^^^^^^
+ .1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000
? +++++++++                                                                                                                                ^^^^^^^

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_minimum_ipv6_netmask" time="0.032" timestamp="2020-10-10T10:03:06">
		<failure message="'10000000.00000000.00000000.00000000.00000[98 chars]0000' != '.1000000000000000.0000000000000000.000000[99 chars]0000'
- 10000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?         -                 -                 -                 -                 -                 -                 -                         -
+ .1000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +                                                                                                                               ++++++++
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 728, in test_minimum_ipv6_netmask
    self.assertEquals('10000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '10000000.00000000.00000000.00000000.00000[98 chars]0000' != '.1000000000000000.0000000000000000.000000[99 chars]0000'
- 10000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?         -                 -                 -                 -                 -                 -                 -                         -
+ .1000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +                                                                                                                               ++++++++

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_minimum_netmask" time="0.015" timestamp="2020-10-10T10:03:06">
		<failure message="'10000000.00000000.00000000.00000000' != '.10000000.00000000.00000000.00000000'
- 10000000.00000000.00000000.00000000
+ .10000000.00000000.00000000.00000000
? +
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 698, in test_minimum_netmask
    self.assertEquals('10000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '10000000.00000000.00000000.00000000' != '.10000000.00000000.00000000.00000000'
- 10000000.00000000.00000000.00000000
+ .10000000.00000000.00000000.00000000
? +

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_one_above_minimum" time="0.004" timestamp="2020-10-10T10:03:06">
		<failure message="'11000000.00000000.00000000.00000000' != '.11000000.00000000.00000000.00000000'
- 11000000.00000000.00000000.00000000
+ .11000000.00000000.00000000.00000000
? +
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 703, in test_netmask_one_above_minimum
    self.assertEquals('11000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11000000.00000000.00000000.00000000' != '.11000000.00000000.00000000.00000000'
- 11000000.00000000.00000000.00000000
+ .11000000.00000000.00000000.00000000
? +

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_well_above_minimum" time="0.003" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11110000.00000000.00000000' != '.11111111.11110000.00000000.00000000'
- 11111111.11110000.00000000.00000000
+ .11111111.11110000.00000000.00000000
? +
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 708, in test_netmask_well_above_minimum
    self.assertEquals('11111111.11110000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11110000.00000000.00000000' != '.11111111.11110000.00000000.00000000'
- 11111111.11110000.00000000.00000000
+ .11111111.11110000.00000000.00000000
? +

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_one_above_minimum_ipv6_netmask" time="0.045" timestamp="2020-10-10T10:03:06">
		<failure message="'11000000.00000000.00000000.00000000.00000[98 chars]0000' != '.1100000000000000.0000000000000000.000000[99 chars]0000'
- 11000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?         -                 -                 -                 -                 -                 -                 -                         -
+ .1100000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +                                                                                                                               ++++++++
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 733, in test_one_above_minimum_ipv6_netmask
    self.assertEquals('11000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11000000.00000000.00000000.00000000.00000[98 chars]0000' != '.1100000000000000.0000000000000000.000000[99 chars]0000'
- 11000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?         -                 -                 -                 -                 -                 -                 -                         -
+ .1100000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +                                                                                                                               ++++++++

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_one_below_maximum_ipv4_netmask" time="0.010" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11111111.11111111.11111100' != '.11111111.11111111.11111111.11111100'
- 11111111.11111111.11111111.11111100
+ .11111111.11111111.11111111.11111100
? +
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 718, in test_one_below_maximum_ipv4_netmask
    self.assertEquals('11111111.11111111.11111111.11111100', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111100' != '.11111111.11111111.11111111.11111100'
- 11111111.11111111.11111111.11111100
+ .11111111.11111111.11111111.11111100
? +

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_one_below_maximum_ipv6_netmask" time="0.039" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11111111.11111111.11111111.11111[98 chars]1110' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111110
?                  -                 -                 -                 -                 -                 -                 ----------
+ .1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111110.0000000
? +++++++++                                                                                                                               ++++++++
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 748, in test_one_below_maximum_ipv6_netmask
    self.assertEquals('11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111110', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111111.11111[98 chars]1110' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111110
?                  -                 -                 -                 -                 -                 -                 ----------
+ .1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111110.0000000
? +++++++++                                                                                                                               ++++++++

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_well_above_minimum_ipv6_netmask" time="0.027" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11111111.11111111.11111111.11111[98 chars]0000' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111110.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?                  -                 ----------                 -                 -                 -                 -                         -
+ .1111111111111111.1111111111111111.1111111111111111.1111111000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +++++++++                                                                                                                       ++++++++
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 738, in test_well_above_minimum_ipv6_netmask
    self.assertEquals('11111111.11111111.11111111.11111111.11111111.11111111.11111110.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111111.11111[98 chars]0000' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111110.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?                  -                 ----------                 -                 -                 -                 -                         -
+ .1111111111111111.1111111111111111.1111111111111111.1111111000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +++++++++                                                                                                                       ++++++++

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_well_below_maximum_ipv4_netmask" time="0.003" timestamp="2020-10-10T10:03:06">
		<failure message="'11111111.11111111.00000000.00000000' != '.11111111.11111111.00000000.00000000'
- 11111111.11111111.00000000.00000000
+ .11111111.11111111.00000000.00000000
? +
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 723, in test_well_below_maximum_ipv4_netmask
    self.assertEquals('11111111.11111111.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.00000000.00000000' != '.11111111.11111111.00000000.00000000'
- 11111111.11111111.00000000.00000000
+ .11111111.11111111.00000000.00000000
? +

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_well_below_maximum_ipv6_netmask" time="0.006" timestamp="2020-10-10T10:03:06">
		<failure message="'1111111111111111.1111111111111111.1111111[90 chars]0000' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000
+ .1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +                                                                                                                                       ++++++++
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 753, in test_well_below_maximum_ipv6_netmask
    self.assertEquals('1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '1111111111111111.1111111111111111.1111111[90 chars]0000' != '.1111111111111111.1111111111111111.111111[99 chars]0000'
- 1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000
+ .1111111111111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000
? +                                                                                                                                       ++++++++

]]>		</failure>
	</testcase>
</testsuite>
