<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="9" failures="0" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestCalculateIpv6Address-20201010131424" skipped="0" tests="14" time="0.031" timestamp="2020-10-10T13:14:25">
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_minimum_ip_and_minimum_subnet" time="0.001" timestamp="2020-10-10T13:14:25"/>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_minimum_ip_and_one_above_minimum_subnet" time="0.001" timestamp="2020-10-10T13:14:25"/>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_minimum_ip_and_well_above_minimum_subnet" time="0.001" timestamp="2020-10-10T13:14:25"/>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_one_above_minimum_ip_and_minimum_subnet" time="0.001" timestamp="2020-10-10T13:14:25"/>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_one_above_minimum_ip_and_one_above_minimum_subnet" time="0.001" timestamp="2020-10-10T13:14:25"/>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_maximum_ip_and_well_below_maximum_subnet" time="0.004" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: 'ffff'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 946, in test_calculate_subnet_in_bit_format_maximum_ip_and_well_below_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111110000.0000000000000000.0000000000000000.0000000000000000')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: 'ffff'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_maximum_ip_and_maximum_subnet" time="0.003" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: 'ffff'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 936, in test_calculate_subnet_in_bit_format_with_maximum_ip_and_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111110')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: 'ffff'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_maximum_ip_and_one_below_maximum_subnet" time="0.003" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: 'ffff'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 941, in test_calculate_subnet_in_bit_format_with_maximum_ip_and_one_below_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111100')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: 'ffff'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_one_below_maximum_ip_and_maximum_subnet" time="0.003" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: 'eeee'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 951, in test_calculate_subnet_in_bit_format_with_one_below_maximum_ip_and_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('eeee:eeee:eeee:eeee:eeee:eeee:eeee:eeee', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111110')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: 'eeee'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_one_below_maximum_ip_and_one_below_maximum_subnet" time="0.003" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: 'eeee'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 961, in test_calculate_subnet_in_bit_format_with_one_below_maximum_ip_and_one_below_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('eeee:eeee:eeee:eeee:eeee:eeee:eeee:eeee', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111100')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: 'eeee'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_well_above_minimum_ip_and_minimum_subnet" time="0.002" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: '11f5'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 921, in test_calculate_subnet_in_bit_format_with_well_above_minimum_ip_and_minimum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('11f5:1a41:9c31:e1a1:1401:a0a5:c2c1:a9d1', '1000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: '11f5'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_well_above_minimum_ip_and_well_above_minimum_subnet" time="0.003" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: '11f5'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 931, in test_calculate_subnet_in_bit_format_with_well_above_minimum_ip_and_well_above_minimum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('11f5:1a41:9c31:e1a1:1401:a0a5:c2c1:a9d1', '1111111111111111.1111111111111111.1111111111111111.1111111111110000.0000000000000000.0000000000000000.0000000000000000.0000000000000000')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: '11f5'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_bit_format_with_well_below_maximum_ip_and_maximum_subnet" time="0.002" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: '55d5'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 956, in test_calculate_subnet_in_bit_format_with_well_below_maximum_ip_and_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('55d5:a4ff:c585:d5c7:b999:c58c:ffd5:d784', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111110')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: '55d5'
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestCalculateIpv6Address" name="test_calculate_subnet_in_ip_format_with_well_below_maximum_ip_and_well_below_maximum_subnet" time="0.002" timestamp="2020-10-10T13:14:25">
		<error message="invalid literal for int() with base 10: '55d5'" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 966, in test_calculate_subnet_in_ip_format_with_well_below_maximum_ip_and_well_below_maximum_subnet
    subnet = subnet_calculator.calculate_ipv6_subnet('55d5:a4ff:c585:d5c7:b999:c58c:ffd5:d784', '1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111000000.0000000000000000.0000000000000000')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 149, in calculate_ipv6_subnet
    binary_group = bin(int(group) & current_netmask_as_integer)
ValueError: invalid literal for int() with base 10: '55d5'
]]>		</error>
	</testcase>
</testsuite>
