<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestValidateIpv6Address-20201004225715" skipped="0" tests="18" time="0.022" timestamp="2020-10-04T22:57:16">
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_abbreviated_zero_at_end_group" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_abbreviated_zero_at_middle_group" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_abbreviated_zero_one_above_eight_groups" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_abbreviated_zero_well_above_eight_groups" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_a_middle_group_negative" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_first_group_negative" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_groups_at_eight" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_groups_one_above_eight" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_groups_one_below_eight" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_groups_well_above_eight" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_groups_well_below_eight" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_last_group_negative" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_letters_between_a_to_f_lowercase" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_letters_between_a_to_f_uppercase" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_letters_between_g_to_z_lowercase" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_letters_between_g_to_z_uppercase" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_ipv6_with_no_groups" time="0.001" timestamp="2020-10-04T22:57:16"/>
	<testcase classname="subnet_calculator_tests.TestValidateIpv6Address" name="test_abbreviated_zero_at_eight_groups" time="0.005" timestamp="2020-10-04T22:57:16">
		<failure message="False is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 344, in test_abbreviated_zero_at_eight_groups
    self.assertTrue(is_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
]]>		</failure>
	</testcase>
</testsuite>
