<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="6" failures="1" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestValidateNetmaskIpFormat-20201006203010" skipped="0" tests="7" time="0.015" timestamp="2020-10-06T20:30:11">
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_netmask_with_octets_at_four" time="0.002" timestamp="2020-10-06T20:30:11">
		<failure message="False is not true" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 446, in test_netmask_with_octets_at_four
    self.assertTrue(is_valid)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_empty_netmask" time="0.003" timestamp="2020-10-06T20:30:11">
		<error message="name 'valid_subnet_ip_regex' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 425, in test_empty_netmask
    is_valid = subnet_calculator.validate_netmask_ip_format('')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 55, in validate_netmask_ip_format
    if (re.match(valid_subnet_ip_regex, netmask)):
NameError: name 'valid_subnet_ip_regex' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_netmask_with_no_digits_in_octet" time="0.002" timestamp="2020-10-06T20:30:11">
		<error message="name 'valid_subnet_ip_regex' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 430, in test_netmask_with_no_digits_in_octet
    is_valid = subnet_calculator.validate_netmask_ip_format('....')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 55, in validate_netmask_ip_format
    if (re.match(valid_subnet_ip_regex, netmask)):
NameError: name 'valid_subnet_ip_regex' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_netmask_with_octets_one_above_four" time="0.002" timestamp="2020-10-06T20:30:11">
		<error message="name 'valid_subnet_ip_regex' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 450, in test_netmask_with_octets_one_above_four
    is_valid = subnet_calculator.validate_netmask_ip_format('255.255.255.0.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 55, in validate_netmask_ip_format
    if (re.match(valid_subnet_ip_regex, netmask)):
NameError: name 'valid_subnet_ip_regex' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_netmask_with_octets_one_below_four" time="0.002" timestamp="2020-10-06T20:30:11">
		<error message="name 'valid_subnet_ip_regex' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 440, in test_netmask_with_octets_one_below_four
    is_valid = subnet_calculator.validate_netmask_ip_format('255.255.255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 55, in validate_netmask_ip_format
    if (re.match(valid_subnet_ip_regex, netmask)):
NameError: name 'valid_subnet_ip_regex' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_netmask_with_octets_well_above_four" time="0.002" timestamp="2020-10-06T20:30:11">
		<error message="name 'valid_subnet_ip_regex' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 455, in test_netmask_with_octets_well_above_four
    is_valid = subnet_calculator.validate_netmask_ip_format('255.255.255.255.255.255.255.0')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 55, in validate_netmask_ip_format
    if (re.match(valid_subnet_ip_regex, netmask)):
NameError: name 'valid_subnet_ip_regex' is not defined
]]>		</error>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestValidateNetmaskIpFormat" name="test_netmask_with_octets_well_below_four" time="0.002" timestamp="2020-10-06T20:30:11">
		<error message="name 'valid_subnet_ip_regex' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 435, in test_netmask_with_octets_well_below_four
    is_valid = subnet_calculator.validate_netmask_ip_format('255')
  File "/home/student/Documents/cs3280project2/src/main/python/subnet_calculator.py", line 55, in validate_netmask_ip_format
    if (re.match(valid_subnet_ip_regex, netmask)):
NameError: name 'valid_subnet_ip_regex' is not defined
]]>		</error>
	</testcase>
</testsuite>
