<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="5" file="subnet_calculator_tests.py" name="subnet_calculator_tests.TestConvertNetmaskBitsToBinary-20201010095331" skipped="0" tests="12" time="0.085" timestamp="2020-10-10T09:53:32">
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_maximum_ipv4_netmask" time="0.001" timestamp="2020-10-10T09:53:32"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_minimum_netmask" time="0.001" timestamp="2020-10-10T09:53:32"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_one_above_minimum" time="0.001" timestamp="2020-10-10T09:53:32"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_netmask_well_above_minimum" time="0.001" timestamp="2020-10-10T09:53:32"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_one_below_maximum_ipv4_netmask" time="0.001" timestamp="2020-10-10T09:53:32"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_well_below_maximum_ipv4_netmask" time="0.001" timestamp="2020-10-10T09:53:32"/>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_maximum_ipv6_netmask" time="0.020" timestamp="2020-10-10T09:53:32">
		<failure message="'11111111.11111111.11111111.11111111.11111111.111[91 chars]1111' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111
?                  -                 -                 -                 -                 -                 -                 - ^^^^^^^^^^^^^^^^
+ 1111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111110000000
? ++++++++++++++++                                                                                                                        ^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 743, in test_maximum_ipv6_netmask
    self.assertEquals('11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111111.11111111.111[91 chars]1111' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111
?                  -                 -                 -                 -                 -                 -                 - ^^^^^^^^^^^^^^^^
+ 1111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111110000000
? ++++++++++++++++                                                                                                                        ^^^^^^^

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_minimum_ipv6_netmask" time="0.018" timestamp="2020-10-10T09:53:32">
		<failure message="'10000000.00000000.00000000.00000000.00000000.000[91 chars]0000' != '1000000.0000000000000000.0000000000000000.000000[91 chars]0000'
- 10000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?         ^                 -                 -                 -                 -                 -                 -                 -
+ 1000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
?        + ^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 728, in test_minimum_ipv6_netmask
    self.assertEquals('10000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '10000000.00000000.00000000.00000000.00000000.000[91 chars]0000' != '1000000.0000000000000000.0000000000000000.000000[91 chars]0000'
- 10000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?         ^                 -                 -                 -                 -                 -                 -                 -
+ 1000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
?        + ^^^^^^^

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_one_below_maximum_ipv6_netmask" time="0.018" timestamp="2020-10-10T09:53:32">
		<failure message="'11111111.11111111.11111111.11111111.11111111.111[91 chars]1110' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111110
?                  -                 -                 -                 -                 -                 -                 ^^^^^^^^^^^^^^^^^
+ 1111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111100000000
? ++++++++++++++++                                                                                                                       ^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 748, in test_one_below_maximum_ipv6_netmask
    self.assertEquals('11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111110', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111111.11111111.111[91 chars]1110' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111111.11111110
?                  -                 -                 -                 -                 -                 -                 ^^^^^^^^^^^^^^^^^
+ 1111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111111111111.1111111100000000
? ++++++++++++++++                                                                                                                       ^^^^^^^

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_well_above_minimum_ipv6_netmask" time="0.012" timestamp="2020-10-10T09:53:32">
		<failure message="'11111111.11111111.11111111.11111111.11111111.111[91 chars]0000' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111110.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?                  -                 -         ---------------- ^                 -                 -                 -                 -
+ 1111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
? ++++++++++++++++                                            ^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 738, in test_well_above_minimum_ipv6_netmask
    self.assertEquals('11111111.11111111.11111111.11111111.11111111.11111111.11111110.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '11111111.11111111.11111111.11111111.11111111.111[91 chars]0000' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 11111111.11111111.11111111.11111111.11111111.11111111.11111110.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?                  -                 -         ---------------- ^                 -                 -                 -                 -
+ 1111111.1111111111111111.1111111111111111.1111111111111111.0000000000000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
? ++++++++++++++++                                            ^^^^^^^

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_well_below_maximum_ipv6_netmask" time="0.010" timestamp="2020-10-10T09:53:32">
		<failure message="'1111111111111111.1111111111111111.11111111.11111[89 chars]0000' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 1111111111111111.1111111111111111.11111111.11111111.11111111.11111111.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?                                           -                  ^^^^^^^^^                 -                 -                 ----------
+ 1111111.1111111111111111.1111111111111111.1111111111111111.1111111110000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
? ++++++++                                                           ++++++++ ^^^^^^^^
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 753, in test_well_below_maximum_ipv6_netmask
    self.assertEquals('1111111111111111.1111111111111111.11111111.11111111.11111111.11111111.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000', binary_netmask)
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '1111111111111111.1111111111111111.11111111.11111[89 chars]0000' != '1111111.1111111111111111.1111111111111111.111111[91 chars]0000'
- 1111111111111111.1111111111111111.11111111.11111111.11111111.11111111.00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000
?                                           -                  ^^^^^^^^^                 -                 -                 ----------
+ 1111111.1111111111111111.1111111111111111.1111111111111111.1111111110000000.0000000000000000.0000000000000000.0000000000000000.0000000000000000
? ++++++++                                                           ++++++++ ^^^^^^^^

]]>		</failure>
	</testcase>
	<testcase classname="subnet_calculator_tests.TestConvertNetmaskBitsToBinary" name="test_one_above_minimum_ipv6_netmask" time="0.002" timestamp="2020-10-10T09:53:32">
		<error message="name 'IPV6_NETMASK_MAX_LENGTH_IPV6_NETMASK_PERIOD_INDEX' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/student/Documents/cs3280project2/src/unittest/python/subnet_calculator_tests.py", line 732, in test_one_above_minimum_ipv6_netmask
    binary_netmask = subnet_calculator.convert_netmask_bits_to_binary('2', IPV6_NETMASK_MAX_LENGTH_IPV6_NETMASK_PERIOD_INDEX)
NameError: name 'IPV6_NETMASK_MAX_LENGTH_IPV6_NETMASK_PERIOD_INDEX' is not defined
]]>		</error>
	</testcase>
</testsuite>
